using System.Collections.Concurrent;

namespace ZuneDeploy.Transport;

/// <summary>
/// Stream to send and receive bytes from a service over a packet stream
/// </summary>
public class ServiceStream : Stream {
    public override bool CanRead => true;
    public override bool CanWrite => true;
    public override bool CanSeek => false;

    public byte StreamId { init; get; }
    public event EventHandler<ushort>? OnBytesWritten;

    private readonly BlockingCollection<Message> _incomingPackets = [];
    private readonly BlockingCollection<Message> _outgoingPackets = [];

    private readonly Queue<MemoryStream> _readQueue = [];
    private readonly MemoryStream _writeBuffer = new();

    internal delegate void CloseStream(byte streamId);
    private readonly CloseStream? _closeStream;

    private bool _disposed = false;

    /// <summary>
    /// Please request a ServiceStream via <see cref="Client.ConnectToService"/>
    /// </summary>
    /// <param name="streamId">The id of the stream as generated by <see cref="StreamCollection"/>></param>
    internal ServiceStream(byte streamId, CloseStream? closeStream) {
        StreamId = streamId;
        _closeStream = closeStream;
    }

    public override int Read(byte[] buffer, int offset, int count) {
        // Drain incoming packets (TODO: this feels kinda unnecessary as we only read one packet at a time anyways)
        while (_incomingPackets.TryTake(out Message? packet)) {
            if (packet != null) {
                _readQueue.Enqueue(packet.Data);
            }
        }

        // If we still don't have any data, block to avoid the BinaryReader calling the Read function repeatedly
        if (_readQueue.Count == 0) {
            _readQueue.Enqueue(_incomingPackets.Take().Data);
        }

        var current = _readQueue.Peek();
        int bytesRead = current.Read(buffer, offset, count);

        // We remove a block from the queue if we read it til the end
        if (current.Position >= current.Length) {
            _readQueue.Dequeue();
        }

        return bytesRead;
    }

    public override void Write(byte[] buffer, int offset, int count) {
        _writeBuffer.Write(buffer, offset, count);
    }

    public override void Flush() {
        var buffer = _writeBuffer.ToArray();
        _outgoingPackets.Add(new Message(StreamId, buffer));
        _writeBuffer.SetLength(0);
        _writeBuffer.Position = 0;
    }

    internal void DeliverMessage(Message message) {
        if (message.StreamId != StreamId) {
            throw new Exception("StreamIds do not match");
        }

        _incomingPackets.Add(message);
    }

    internal bool CollectMessage(out Message? item) {
        return _outgoingPackets.TryTake(out item);
    }

    internal void InvokeOnBytesWritten(ushort bytes) {
        OnBytesWritten?.Invoke(null, bytes);
    }

    /// <summary>
    /// Clean up the stream resources
    /// </summary>
    /// <param name="disposing">true if called from Dispose(), false if called from finalizer</param>
    protected override void Dispose(Boolean disposing) {
        if (_disposed) {
            return;
        }

        if (disposing) {
            _closeStream?.Invoke(StreamId);
            _disposed = true;
        }
    }

    public override long Length => throw new NotSupportedException();
    public override long Position { get => throw new NotSupportedException(); set => throw new NotSupportedException(); }
    public override long Seek(long offset, SeekOrigin origin) => throw new NotSupportedException();
    public override void SetLength(long value) => throw new NotSupportedException();
}
