name: Publish App Image
"on":
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:26.04
    steps:
      - name: Install git
        run: apt-get update; apt-get install -y git
      - name: Checkout git repository
        uses: actions/checkout@v6
        with:
          lfs: true
          submodules: true
          fetch-depth: 0
      - name: Install Dependencies
        run: scripts/install-dependencies.sh
      - name: Build App Image
        run: scripts/build-app-image.sh
